package test;

import com.github.javafaker.Faker;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import site.SHA512.Sha512;

import java.nio.charset.StandardCharsets;


public class SHA512Test {
    @Test
    @DisplayName("Expect for any word the message must have same size")
    public void givenRadomStringValueSizeMustBeEqual128() {
        Faker faker = new Faker();
        byte[] randomWordBytes = faker.name().fullName().getBytes(StandardCharsets.UTF_8);
        Sha512 shaAlgorithm = new Sha512(randomWordBytes);

        String hashedRandomWord = shaAlgorithm.encrypt();

        Assertions.assertEquals(128, hashedRandomWord.length());
    }

    @Test
    @DisplayName("Expect the hash generated is the same as generated by other language")
    public void givenAValueHashMustBeEqualASHA512FromLanguage() {
       String toHash = "Abobora";
       String hashedHardcodedWord = "550c1e20fd64ef92109742e4fd9539140c6f4dd39bbdbad5298f66afd947f2bca766d273e50abef12283fbe117f9b1f56969bedf8894e4d09a3c5aaee46fdd76";
        byte[] randomWordBytes = toHash.getBytes(StandardCharsets.UTF_8);
        Sha512 shaAlgorithm = new Sha512(randomWordBytes);

        String hashedWord = shaAlgorithm.encrypt();

        Assertions.assertEquals(hashedHardcodedWord,hashedWord);
    }
}
